#docker-compose.yml
version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: ${NAME_CONTAINER}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine3.21
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  db_data: